version: '3'
services:
  openai_proxy:
    image: nginx:latest
    volumes:
      - ./openai_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  download_proxy:
    build: ./download_proxy
    ports:
      - "3128:3128"

  # squid:
  #   image: sameersbn/squid:3.5.27-2
  #   volumes:
  #     - ./squid.conf:/etc/squid/squid.conf
  #   ports:
  #     - '3128:3128'

  # download_proxy:
  #   # image: nginx:latest
  #   image: jungsoft/alpine-nginx-forward-proxy
  #   volumes:
  #     - ./download_proxy.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - '3128:3128'
